/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_TRANSFER_H_RPCGEN
#define _FILE_TRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct FileData {
	char *filename;
	struct {
		u_int content_len;
		char *content_val;
	} content;
	bool_t is_last_chunk;
};
typedef struct FileData FileData;

#define FILE_TRANSFER_PROG 0x23451111
#define FILE_TRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define upload_file 1
extern  int * upload_file_1(FileData *, CLIENT *);
extern  int * upload_file_1_svc(FileData *, struct svc_req *);
extern int file_transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define upload_file 1
extern  int * upload_file_1();
extern  int * upload_file_1_svc();
extern int file_transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_FileData (XDR *, FileData*);

#else /* K&R C */
extern bool_t xdr_FileData ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_TRANSFER_H_RPCGEN */
